#!/bin/bash
# =============================================================
# Phase 1: Immediate VM Lockdown
#
# Runs as root via port 22 within seconds of VM creation.
# Goal: lock the VM down before any attacker can find it.
#
# NO apt-get installs — pure configuration of pre-installed
# Ubuntu 24.04 packages. Expected runtime: < 30 seconds.
#
# Usage: harden-phase1.sh <new_username> <ssh_port>
# Pre-condition: /tmp/provisioner_pub_key must exist (uploaded
#                by the orchestrator before calling this script)
# =============================================================

set -euo pipefail

NEW_USER="$1"
SSH_PORT="$2"

LOGFILE="/var/log/harden-phase1.log"
exec > >(tee -a "$LOGFILE") 2>&1

log()  { echo "[$(date '+%H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date '+%H:%M:%S')] [WARN]  $*"; }
die()  { echo "[$(date '+%H:%M:%S')] [ERROR] $*"; exit 1; }

[[ -z "${NEW_USER:-}" || -z "${SSH_PORT:-}" ]] && die "Usage: $0 <username> <ssh_port>"
[[ -f /tmp/provisioner_pub_key ]] || die "Public key not found at /tmp/provisioner_pub_key"

log "=== Phase 1: Immediate Lockdown Starting ==="
log "User: $NEW_USER | SSH Port: $SSH_PORT"

# -------[ 1. Create unprivileged user + sudoers ]-------
log "Creating user $NEW_USER..."
useradd -m -s /bin/bash "$NEW_USER"
mkdir -p "/home/$NEW_USER/.ssh"
cp /tmp/provisioner_pub_key "/home/$NEW_USER/.ssh/authorized_keys"
rm -f /tmp/provisioner_pub_key
chmod 700 "/home/$NEW_USER/.ssh"
chmod 600 "/home/$NEW_USER/.ssh/authorized_keys"
chown -R "$NEW_USER:$NEW_USER" "/home/$NEW_USER/.ssh"
echo "$NEW_USER ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/90-$NEW_USER"
chmod 440 "/etc/sudoers.d/90-$NEW_USER"
visudo -c -f "/etc/sudoers.d/90-$NEW_USER" || die "sudoers validation failed"
log "User created."

# -------[ 2. Lock root account ]-------
passwd -l root
log "Root account locked."

# -------[ 3. Random hostname (obscures server purpose) ]-------
RANDOM_HOSTNAME="node-$(openssl rand -hex 4)"
hostnamectl set-hostname "$RANDOM_HOSTNAME"
# Update /etc/hosts so the hostname resolves locally
sed -i "/127.0.1.1/d" /etc/hosts
echo "127.0.1.1 $RANDOM_HOSTNAME" >> /etc/hosts
log "Hostname randomised to: $RANDOM_HOSTNAME"

# -------[ 4. Legal deterrent banner ]-------
cat > /etc/issue.net << 'BANNER'
*******************************************************************************
*                         AUTHORIZED ACCESS ONLY                              *
*                                                                             *
*  This system is monitored. All activities are logged. Unauthorized access   *
*  or use is prohibited and may result in criminal prosecution.               *
*                                                                             *
*******************************************************************************
BANNER
cp /etc/issue.net /etc/issue
chmod 644 /etc/issue.net /etc/issue
chown root:root /etc/issue.net /etc/issue
log "Login banner written."

# -------[ 5. Disable ctrl-alt-del emergency reboot ]-------
systemctl mask ctrl-alt-del.target
log "ctrl-alt-del reboot disabled."

# -------[ 6. Disable socket activation & write hardened sshd_config ]-------
# Ubuntu 24.04 uses ssh.socket (systemd socket activation) which listens on
# port 22 and passes the fd to sshd — ignoring the Port directive in sshd_config.
# We must disable ssh.socket so sshd manages its own listening socket.
systemctl disable --now ssh.socket 2>/dev/null || true
systemctl enable ssh.service
log "ssh.socket disabled — sshd will manage its own listening socket."
mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config << EOF
# Phase 1 hardened sshd_config — generated by provisioner
# Phase 2 adds additional crypto hardening via the drop-in below.
Include /etc/ssh/sshd_config.d/*.conf

Port $SSH_PORT
AddressFamily inet
ListenAddress 0.0.0.0

# Authentication — key only, no root, no passwords
PermitRootLogin no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

# Strict user allowlist
AllowUsers $NEW_USER

# Connection hardening
MaxAuthTries 3
LoginGraceTime 20
MaxSessions 3
MaxStartups 3:50:10

# Disable all forwarding
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
DisableForwarding yes

# Misc
UsePAM yes
PrintMotd no
TCPKeepAlive no
PermitUserEnvironment no
Banner /etc/issue.net
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

sshd -t || die "sshd config validation failed — aborting before restart"
log "sshd_config written and validated."

# -------[ 7. UFW firewall (pre-installed on Ubuntu 24.04) ]-------
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow in on lo
ufw allow out on lo
ufw deny in from 127.0.0.0/8   comment "block external loopback"
ufw deny in from ::1            comment "block IPv6 loopback"
ufw allow "$SSH_PORT/tcp"       comment "hardened SSH"
ufw --force enable
log "UFW enabled: deny-all incoming, SSH port $SSH_PORT open."

# -------[ 8. TCP wrappers (extra layer on top of UFW) ]-------
echo "ALL: ALL" > /etc/hosts.deny
echo "sshd: ALL" > /etc/hosts.allow
chmod 644 /etc/hosts.deny /etc/hosts.allow
log "TCP wrappers: deny all, allow sshd."

# -------[ 9. Critical sysctl hardening (takes effect immediately) ]-------
cat > /etc/sysctl.d/10-phase1-hardening.conf << 'EOF'
# Anti-spoofing & anti-redirect
net.ipv4.tcp_syncookies = 1
net.ipv4.ip_forward = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Reverse path filtering (prevents IP spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# ICMP hardening
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable IPv6 entirely
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

# Kernel hardening
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 1
fs.suid_dumpable = 0
EOF
sysctl -p /etc/sysctl.d/10-phase1-hardening.conf
log "Kernel sysctl hardening applied."

# -------[ 10. Disable core dumps ]-------
grep -q "^\* hard core 0" /etc/security/limits.conf 2>/dev/null \
    || echo "* hard core 0" >> /etc/security/limits.conf
log "Core dumps disabled."

# -------[ 11. Done — sshd restart is handled by the orchestrator ]-------
# We do NOT restart sshd here. The orchestrator (provision.py) restarts it
# through the same SSH session after this script exits.  On Ubuntu 24.04
# ssh.service uses KillMode=process, so the existing session child process
# survives while the main listener restarts on the new port.
log "Phase 1 complete. sshd config written for port $SSH_PORT."
log "Orchestrator will restart sshd next."
log "Log saved to: $LOGFILE"

exit 0
